site_name: 'weather'
site_description: 'Main documentation for weather'
repo_url: https://github.com/jaysuzi5/weather
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'